language: go

sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.ccm/repository
    - $HOME/.local/lib/python2.7

matrix:
  fast_finish: true

env:
  global:
    - GOMAXPROCS=2
  matrix:
    - CASS=2.0.17
      AUTH=false
    - CASS=2.1.12
      AUTH=false
    - CASS=2.2.4
      AUTH=true
    - CASS=2.2.5
      AUTH=false

go:
  - 1.6
  - 1.7

# hostname setup for ec2_test
before_install:
  - sudo chmod uga+w /etc/hosts
  - sudo echo -e "\n10.10.220.253\tec2.test.host.gocql\n10.10.220.254\tec2.test.host.gocql\n" >> /etc/hosts

install:
  - pip install --user cql PyYAML six
  - git clone https://github.com/pcmanus/ccm.git
  - pushd ccm
  - ./setup.py install --user
  - popd
  - go get .

script:
  - set -e
  - PATH=$PATH:$HOME/.local/bin bash integration.sh $CASS $AUTH ec2_test
  - go vet .

notifications:
  - email: false
